server:
  port: 8031
spring:
  application:
    name: alibaba-order-seata
  cloud:
    alibaba:
      seata:
        tx-service-group: my_test_tx_group  # 这是一个坑service.vgroupMapping.my_test_tx_group=default里面的my_test_tx_group和此处必须一样
#    nacos:
#      server-addr: 127.0.0.1:8848 # 路径
#      discovery:
#          username: nacos
#          password: nacos
#          namespace: public
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_chat?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 192820
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小
      initialSize: 5
      #最小值
      minIdle: 5
      #最大值
      maxActive: 20
      #最大等待时间，配置获取连接等待超时，时间单位都是毫秒ms
      maxWait: 60000


#mybatis配置
mybatis:
  #配置SQL映射文件路径
  mapper-locations: classpath:mapper/*.xml
  #配置别名
  type-aliases-package: com.seata.order.pojo
  #驼峰命名
  configuration:
    map-underscore-to-camel-case: true
seata:
  registry:
    type: nacos
    nacos:
      server-addr:  127.0.0.1:8848
      username: nacos
      password:  nacos
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      username:  nacos
      password:  nacos
  #      group: SEATA_GROUP
  #      application:  seata-server